### ISSUE TITLE
Feature/Athlete Revamp/Slot Card

### ISSUE THREAD

**Issue by delasous** [eisbuk/EisBuk#484]
Covers Figma component mocks:
- Slot
- Calendar Slot
- Slot Action
- Time
- Booking Type

## Discussion
- [ ]  Existing “SlotCard” refers to Admin views, the current equivalent of this component is “BookingCard”
    - Should we use SlotCard name here, and change Admin component to “AdminSlotCard” (Iif Alex revamps Admin views, it could come into line with this Athlete component ?)
- [ ]  “With Notes” variant of BookingCard does not seem to be accounted for in new mocks?
    - Could just do ourselves by making space underneath the time or “Rink 1”?
- [ ]  “Booking countdown” is another Athelete component that isn’t represented in news mocks - is it being used?
- [ ]  Update Storybook so that new/Athlete component tickets are grouped?

**Tasks (Tickets):**
- Add/update *local component files* (consistent/better name for this? - e.g small unit-parts that assemble into exported component, and sit in folder next to it, like `SlotCard/localUnit.tsx`):
    - Update `BookingCard/Duration.tsx` ⇒ `SlotCard/DurationBadge.tsx` or `TimeBadge.tsx` (I like the use of “Badge” or “Pill” in this context of displaying concise critical facts in a little borderd box to user)
        - Did we decide here on our preference for handling pesky 0.5h or 30m with new mock? I see logic for it is already there in `Duration.tsx`
    - Update global SlotTypeIcon (also used in Admin views) to use current styles; or create new *local* `SlotCard/SlotTypeIcon.tsx`, for use in new Athlete views only (and lift out later)?
    - Add “BookingsButton” (if we keep current “BookingsCard” theme), or “SlotActionButton” if we change to SlotCard
        - Uses Badge above
- Update Booking Card default & variants (”Booked”, “Faded”, “Disabled”, “Calendar Variant”) to use new mock styles.

**Comment by delasous** [comment]
Existing `BookingsCard` uses one or more of existing `Duration` to indicate slot length. Alex's mock uses box scale/size to indicate it => critical style update to BookingsCard includes size difference relative to its duration.

**Comment by ikusteu** [comment]
I don't think we need an explicit with-notes variant. Mere presence/absence of notes will decide if they will get rendered or not.

**Comment by ikusteu** [comment]
> “Booking countdown” is another Athelete component that isn’t represented in news mocks - is it being used?

Yeah, we need that. I feel it could be positioned inline with date navigation, but let's leave that to alex

**Comment by ikusteu** [comment]
> Existing “SlotCard” refers to Admin views, the current equivalent of this component is “BookingCard”
Should we use SlotCard name here, and change Admin component to “AdminSlotCard” (Iif Alex revamps Admin views, it could come into line with this Athlete component ?)

I would actually prefer `IntervalCard` in this context and leave the `SlotCard` as it is - The cards (for booking), that Alex created, actually display interval, while `SlotCard` (admin view represents an entire slot)

**Comment by ikusteu** [comment]
We should also reimplement (refresh) the existing BookingCardGroup component.

**Comment by ikusteu** [comment]
> Update Storybook so that new/Athlete component tickets are grouped?

Oh, yeah…we should definitely create nicer stories

**Comment by ikusteu** [comment]
> Did we decide here on our preference for handling pesky 0.5h or 30m with new mock? I see logic for it is already there in Duration.tsx

Yeah…I’ve created logic for those as failsafe, I really think @silviot should put his foot down on this

**Comment by ikusteu** [comment]
> Update global SlotTypeIcon (also used in Admin views) to use current styles; or create new local SlotCard/SlotTypeIcon.tsx, for use in new Athlete views only (and lift out later)?

Definitely. It should be it’s own atom. It should have three type variants: ice, off-ice-dancing and off-ice-gym. @silviot can you confirm that this is the latest consensus.
Additionally, if, in the future, we need different sizes for the type icon (could we call this ‘TypeBadge’ as well 🤔), we can simply add predetermined size variants

**Comment by ikusteu** [comment]
☝️ I think it’s safe to make the new type icon global to begin with

**Comment by ikusteu** [comment]
> Update existing BookingsCard default & variants (”Booked”, “Faded”, “Disabled”, “Calendar Variant”) to use new mock styles.

Is it safe to assume that the second colour variant for each slot card (in the mockup) is faded - it's described as hovered, but I think it should be "faded" (When one interval for a slot is selected, all the rest of the intervals are in "faded" state)

**Comment by ikusteu** [comment]
Opened up a `BookingsButton` ticket -  #486 

I think the name makes sense regardless of our choice for Slot/Booking/Interval card naming, but let me know if your opinion differs

**Comment by ikusteu** [comment]
☝️ we should decide on which variant to use for duration 1.5h in #486

**Comment by delasous** [comment]
Edit: add discussion and task points for Slot Group / Day Container

**Comment by ikusteu** [comment]
> Update BookingCardGroup ⇒ IntervalCardGroup to use new IntervalCard, and any styles (should just be typography of heading, looks like element flow is already there)

I don't know what typography you're referring to, but `BookingCardGroup` (as it's currently named) serves as only a stateful container for `BookingCard`s

Also...my bad, I didn't provide JSDoc for `BookingCardGroup`...The sole purpose of `BookingCardGroup` is to take in a whole slot and render intervals for that slot. Additionally, it keeps the currently booked interval in state, shows that interval as active (the prop name on `BookingCard` is `booked`, but should probably be `active`) and adds `fade` to all the rest of the intervals for that slot. This is used to provide visual cues that only one interval can be booked per slot (and booking a different one cancels the previously booked interval).
So...not to be confused with `SlotsDayContainer`, which has it's heading and renders all `BookingCardGroup`s for the day. In the mockup, only one `BookingCardGroup` is shown for a day, but there'll be multiple ones as there are multiple slots per day.

**Comment by ikusteu** [comment]
Ok...so, looking at all the cards, I propose three variants:
- Booking (default)
- Calendar 
- Brief (or "reduced", or something like that...I'm not a big fan of any of those names): 
  - the one with limited elements, used for confirmation dialog
  - no button
  - no type icon
  - no notes
  - only time string and date

Those variants would be combined with `active`/`faded` state, `type` and (calculated) duration to provide styling/functionality:
- "calendar" and "brief" (working name) would be `active` by default: 
  - calendar allows only "cancel" button
  - brief has no button
  - both show outline with respect to type (for colour)
  - faded state should not be considered (have no effect) for neither of the two
  - Alex didn't provide different renderings of calendar with respect to duration (all examples are two hours), but I gather the size will be the same, regardless of duration for those two variants
- "booking" depends on `active` and/or `faded` state:
  - if active shows outline, colour with respect to type
  - if faded, shows faded element (I believe that's the second colour variant in Figma)
  - shows size depending on duration
  - shows "book"/"cancel" button depending on `active` state

**Comment by ikusteu** [comment]
We can leave those states ☝️ two separate booleans, or group them into enum:
- default (default)
- active
- faded

as active and faded shouldn't both be true at the same time

**Comment by ikusteu** [comment]
Sorry...I realised just now that this is for "SlotCard"/"IntervalCard"...I thought it was a general discussion for customer view UI updates

**Comment by delasous** [comment]
Closing as I feel all notes have been moved to smaller, more concrete tickets.
