### ISSUE TITLE
Feature: ActionDialog: 3 pts

### ISSUE THREAD

**Issue by delasous** [eisbuk/EisBuk#487]
## Component: ActionDialog

**Description:** A dialog that will be used across the app as confirmation dialog. In case of `customer_area`, it will show a simple variant of #495 (details of the interval), and two buttons: to either reject or confirm the action.

Existing `ConfirmDialog` can be used as a reference to build atop.

**Mockup:**
[![Screenshot from 2022-06-08 12-11-03](https://user-images.githubusercontent.com/396425/172591706-3bfdd16b-099e-4d4c-b888-c960385df818.png)](https://www.figma.com/file/oAzgMQW7vCaZAYmL58lxeo/Eisbuk?node-id=1514%3A36896)

#### Props:

- **title** (optional: string):
  - if not provided, only the message (**children**) is shown
- **children** (optional: JSX.Element):
  - some simple prompts might only feature the **title** so this is optional
  - this is here so that we can pass some "content" to the dialog (as in the case of booking confirmation where the simple `IntervalCard` is shown)
- **confirmLabel** (optional: string):
  - label on confirm button
  - if not provided should fall back to something like "confirm" or "yes"
- **cancelLabel** (optional: string):
  - label on cancel button
  - if not provided should fall back to something like "cancel" or "no"
- **open** (required: boolean)
- **onClose** (required: Function): click handler used to close the modal in some outer state
- **onConfirm** (required: Function): handler for confirming action

#### Storybook:

- Default: we should provide some title and use the default values for **confirmLabel** and **cancelLabel**
- ...(variants):
  - this isn't a constrained choice of variants, but rather usage of this component "in the wild"
  - initially it should feature booking confirmation, but get extended with more examples as the mockup evolves

#### Functionality:

- should close itself on cancel
- should call to **onConfirm** and close itself on confirmation

#### Depends on:

- [ ] #486
- [ ] #495 (doesn't depend directly, but would be good to wait for it for stories)

#### TODO:

- [ ] Create prop interface confirming to the spec and TDD the functionality
- [ ] Replace MUI `Dialog`, `DialogTitle`, `DialogContent`, `DialogActions` with our tailwind styles to Figma mock.
- [ ] Replace MUI `Button` with our own local (`ActionDialog/Button.tsx`), which conforms to [this mock](https://www.figma.com/file/oAzgMQW7vCaZAYmL58lxeo/Eisbuk?node-id=1520%3A27766), and captures hoverable state
- [ ] Create stories

**Comment by ikusteu** [comment]
I like the labels, I would expand this to include it's own buttons...I see these buttons being specific (they're hoverable, unlike others)...no need for different component, could just be part of this component (just thinking out loud)

**Comment by ikusteu** [comment]
I suggest the content being passed as `children` as [this]() is used to confirm interval cancellation (with a restricted version of interval card passed) and I imagine some other use cases would just pass string to be rendered in the body of the dialog

**Comment by ikusteu** [comment]
> There is an existing component global/ConfirmDialog.tsx which seems to cover the general "reject/confirm" dialog logic. Can we update this directly, or should we clone it as its also being leveraged in Admin views?

I suggest creating a new component in `packages/ui` (when it's created), but we can probably reuse some of the code in the existing component

**Comment by ikusteu** [comment]
I would also add `title` prop and have the title always be string and styled the same (as in interval cancellation example)

**Comment by ikusteu** [comment]
> I like the labels, I would expand this to include it's own buttons...I see these buttons being specific (they're hoverable, unlike others)...no need for different component, could just be part of this component (just thinking out loud)

> Replace MUI Button with our own local (ActionDialog/Button.tsx), which conforms to [this mock](https://www.figma.com/file/oAzgMQW7vCaZAYmL58lxeo/Eisbuk?node-id=1520%3A27766), and captures hoverable state

I don't think there's a need for different component. I know I suggested it earlier, but that was before dreaming up the #486 spec. This can be don using the global button component (`lg` variant) and just passing additional styles through `className` -- I imagine those styles being different `bg-<colour>` and `hover:bg-<colour>`.

**Comment by ikusteu** [comment]
**Edit:** rearranged the spec clearly state all the requirements/progress
