### ISSUE TITLE
Feature: Calendar Nav: 3 pts

### ISSUE THREAD

**Issue by delasous** [eisbuk/EisBuk#493]
# Component: Calendar Nav

## Requirements
**Mockup:**
- [Bar ![Image](https://user-images.githubusercontent.com/396425/172585443-e0f076d0-d721-4b04-bb9f-0561138c4c4b.png)](https://www.figma.com/file/oAzgMQW7vCaZAYmL58lxeo/Eisbuk?node-id=1505%3A27272)
- [Buttons ![Image](https://user-images.githubusercontent.com/396425/172585365-88beba64-4950-45fd-a232-8cc0d97daa94.png)](https://www.figma.com/file/oAzgMQW7vCaZAYmL58lxeo/Eisbuk?node-id=1505%3A26848)

**Description**
A nav bar for changing the date interval of displayed IntervalCards. Will be used in the layout shared by Customer Area > "Book" and "Calendar" pages. The new component should be extended from the existing `DateNavigation.tsx`.

**Tasks** 
- [ ]  Create new `DateNavigation.tsx` in `packages/ui`, using existing component that is shared with Admin UI as a base:
  - [ ]  Replace MUI IconButton and Chevron's with our own local component and svg's, styled to mocks.
  - [ ] Replace MUI AppBar (& ToolBar?) with our own container styled to mock
  - [ ] Replace MUI Typography > Date Title, with our own local `DateBadge` (name?)
  - [ ] Remove DateSwitcher
    - [x] Related: `BookingsCalendar` Page "jump" should be updated to transition by "month"
 - [ ] Add a container spaced to the right of the bar (similar to `<div className={classes.childrenContainer}>` in existing component)`, to render children if they are passed. Will be used to display #496.
   - [ ] @ikusteu can we remove "toggleState" / "toggleButton" logic for now. It will be used in Admin variant of this nav, but could be re-introduced when we get there?

**Comment by ikusteu** [comment]
I would also have #496 displayed here (on the right side perhaps). We don't need to hard code it, however. I can be just a container (right side of the grey navbar), and pass the countdown as JSX
