### ISSUE TITLE
Feature: CustomerNavigation.tsx re-write

### ISSUE THREAD

**Issue by delasous** [eisbuk/EisBuk#501]
**Tasks:**
- [ ]  Update `customer_area/CustomerNavigation/CustomerNavigation.tsx`:
  - [ ]  Use #500 
  - [ ]  Add array of Links (props in TopBar spec: href/to, label, icon)
  - [ ]  Replace MUI AppBar & Container with our own tailwind styled boxess
  - [ ] Remove "BookOffIce" route
  - [ ] Adds a space (and timeout clear logic) for #489
