### ISSUE TITLE
Feature: UserAvatar: 2 pts

### ISSUE THREAD

**Issue by ikusteu** [eisbuk/EisBuk#512]
## Component: UserAvatar

**Description:** An update on `EisbukAvatar` to conform to the new mockup

[**Mockup (avatar on the right hand side):**
![Screenshot from 2022-06-07 12-48-38](https://user-images.githubusercontent.com/396425/172362035-a884f322-2292-4ae2-9a39-8b129623b79e.png)](https://www.figma.com/file/oAzgMQW7vCaZAYmL58lxeo/Eisbuk?node-id=1514%3A33847)

#### Props (a subset of `CustomerBase` interface):

- **name** (required: string):
- **surname** (required: string):
- **avatar** (optional: string):
  - this isn't used currently and the `CustomerBase` interface should be extended with it
  - alternatively it can be `image` or `profilePicture`, etc.
  - in absence of this property (or in case of an empty string), some fallback should be shown
- **category** (required: string):
  - we've prevouisly used this to render different mask (border radius) for the image, but can be omitted if not necessary anymore

#### Styles:

- Category dependant mask ??

#### Storybook (stories):

- Default
- Categories (if mask will still be used)

#### Functionality (should be tested):

- null

### Possible enhancements:

- null

#### TODO:

- [x] extend `CustomerBase` with `avatar`
- [x] provide fallback if `avatar` not specified (we can reuse the initials logic)
- [x] finish the component
