### ISSUE TITLE
Page: CustomerAreaPage

### ISSUE THREAD

**Issue by ikusteu** [eisbuk/EisBuk#540]
## Page: CustomerAreaPage

**Description:** A page component to be used for `/customer_area` (booking) route.

**Mockup:** [Figma](https://www.figma.com/file/oAzgMQW7vCaZAYmL58lxeo/Eisbuk?node-id=1503%3A26254)

### Requirements:

Should use the components created in this sprint to render the customer area page to mock.
Should read and display data from store:

- customer (current customer)
- slots available for booking (with respect to customer's category)
- booked slots

Unlike the old page component, it seems that the split between ice/off-ice slot is not necessary (they will be visually different using IntervalCard styles)

Previous version also featured subroutes for `book-ice`, `book-off-ice` and `calendar`, but I feel this can just be local state.

#### Elements:

- Layout:
  - components:
    - #500
    - #493
    - #519
    - #496
  - The page layout comprised of standard `Layout` component and `CalendarNav`
  - The `Notifications` part of the layout component should be `NotificationContainer` component (hooked to the store and in charge of it's own updates)
  - Calendar nav should dispatch the date change to redux
- Days:
  - components:
    - #495
    - #537

#### Props:

- No props, all data should be read from the app (Redux) store

#### Storybook (stories):

- null

#### Styles:

- the content should utilize the `content-container` class to position everything centrally

#### Functionality (should be tested):

- Should switch date (dispatch against Redux)
- Should book/cancel intervals (dispatch against Redux)

#### Depends on:

    - #500
    - #493
    - #519
    - #496
    - #495
    - #537

#### TODO

- [ ] Set up components on the screen (styles and all)
- [ ] Set up local state with `Book` and `Calendar` buttons
- [ ] Check the selector logic from the old page component (for slots/bookings, etc.)
- [ ] Write simple tests (book, date change)
- [ ] Check for additional tests (in the old page)
