### ISSUE TITLE
Delete checklist (client package)

### ISSUE THREAD

**Issue by ikusteu** [eisbuk/EisBuk#574]
# Delete checklist (client package)

This is a checklist of all artifacts (components, hooks, functions) that can be deleted as being replaced by rehauled versions or have become obsolete.

I've imagined this ticket as being open for the duration of Admin incremental rehaul, rebased each time one of the dependency tickets has been closed and deleting artefacts as soon as they have been replaced.

## Components:

- [x] `atoms/BookingCard`
- [x] `atoms/BookingCardGroup`
- [x] `atoms/BookingsCountdown`
- [x] `global/ConfirmDialog` - depends on #569 
- [x] `layout/*` - TBD
- [x] `auth/*` - TBD
- [x] `users/EisbukAvatar` - depends on #570 
- [x] `customers/CustomerForm` - depends on #572 
- [x] `Notifier.tsx` - depends on #571 
- [x] `atoms/NotificationButton.tsx` - depends on #571 
- [x] `atoms/AttendanceCard/*` - depends on #573 
- [x] `atoms/CustomerCard/*` - depends on #572 
- [x] `atoms/CustomerList/*` - depends on #573 
- [x] `atoms/DateNavigation/*` - depends on #570 
- [x] `atoms/SlotsDaycontainer/*` - depedns on #568 
- ...more TBD

## Store:

- [x] `store/actions/appActions.ts`:
  - depends on #<notifications replace>
  - artifacts to delete:
    - enqueueNotification
    - closeSnackbar
    - removeSnackBar
    - showErrSnackbar
    - appReducer should be updated to exclude the aforementioned actions
    - getNotifications in `store/selectors/app.ts`

## Dependencies:
- [x] `notistack`:
  - depends on #571
