### ISSUE TITLE
Enhancement: CustomerForm admin upgrades & integration

### ISSUE THREAD

**Issue by delasous** [eisbuk/EisBuk#642]
WIP

Admins can edit the same details as Customers + a few additional fields. The admin view currently uses the old CustomerForm for this, which is accessed via the Athletes avatar > Pencil Icon. We should enhance the CustomerForm with additional admin fields, which are displayed only when an `isAdmin` flag is true. The form under CustomerArea > Profile should then be repurposed for Admin and Customer use: the same way that clicking on an Athletes Avatar > Bookings redirects an Admin to the CustomerArea > Bookings subview, the Pencil Icon should redirect to the Profile subview.

### Tasks
- [ ] Add additional admin fields to CustomerForm, and toggle them with an `isAdmin` flag. This includes:
    1. Category
    2. Card Number
    3. Extended Booking Date? => Discuss if this should be part of form. It is currently managed as action at same level as Pencil Icon, Bookings, Send Bookings Link...
        - Note: This button currently opens yet another modal within a modal to confirm then action: this needs a redesign.
- [ ] Route Pencil Icon to CustomerArea > Profile (see notes below):
    1. Path needs to indicate which subview to render. Defaults to "Bookings" now.
    2. `isAdmin` = true also needs to be communicated
- [ ] Remove old CustomerForm components in client package

### Notes
1. Routing from Admin to CustomerArea > Profile
    1. In `AppContent.tsx` at root of src
    3. Customer_Area is currently defined as:
        ```javascript
          <Route
              path={`${Routes.CustomerArea}/:secretKey`}
              component={CustomerAreaPage}
          />
       ```
    4. On admin customers > CustomerGrid > CustomerCard (which is “display” of CustomerForm, there are also buttons, one of which “Bookings” onClick will take you to customer_area:secretKey) > ActionButtons. It does this by:
        ```javascript
        import { useHistory } from "react-router-dom";

        const history = useHistory();
        
        // redirect to customers `bookings` entry flow
        // ITS NOT THE ID, its the secretKey
        const bookingsRoute = `${Routes.CustomerArea}/${customer?.secretKey}`;
        const redirectToBookings = () => history.push(bookingsRoute);
        
        onClick={redirectToBookings}
        ```
    5. Ends up with URL `http://localhost:3000/customer_area/cf31f96b-4df7-4891-9d66-9fd5f365655e`
    6. Customer_Area route has no knowledge of which view to render in ⇒ it defaults to “BookView” (set in useState at top of customer_area/index). This works for "Bookings" button link. But we will need to include something in the path to set the subview.
