### ISSUE TITLE
Allow athletes to self register

### ISSUE THREAD

**Issue by silviot** [eisbuk/EisBuk#656]
Athletes should be able to create an entry for themself without any action required by admins.
The flow should be:
* Athletes are provided with a URL and an organization-wide weak secret (a passphrase that can be changed in the organization settings)
* Athletes log into the system (actually they create a user) with the existing form
* If there is no athlete entry for the currently logged in user, we present a form to fill out. Email or phone will be pre-filled with the value used for login.
* Upon succesful form submission a new entry will be created in the `customers` collection, and the trigger will in turn assign it a secret key and create an entry in the `bookings` collection with the secret key. The user will be redirected to their booking management page at this point.

The newly created user will have all categories associated with them, so the system should allow them to book any slot (until an admin comes in and assigns categories to restrict what they can book).

## Task breakdown

The initial step is already developed. If a user doesn't exist, they can register and a new auth user will be created. There are still a couple of things we should do update in that regard:

- [x] Differentiate sign in and register buttons on inital auth screen
- [x] Don't require `name and surname` field, or make it two fields: `name` and `surname` (anybody's input/preference appreciated here)

After the user is registered, a modal/slide-over/route for registration should be open (we can probably reuse the UI for CustomerProfileForm) at which point, after all of the required fields are filled, the user will get created in firestore and await admins "approval" (assigning a category) at which point we should probably show some message stating: you haven't been assigned to any category, contact your admin, etc.

### UI

- [x] Reuse the `CustomerProfileForm`:
  - we will need to decouple the logic of the "Edit" button/state (should probably lift it out) as it's unnecessary for self registration logic
  - my suggestion would be to create a route for self registration, which would present the `CustomerProfileForm`, without the `isEditing` toggle (it would always be `true`) as that seems to be the quickest solution
- [x] Add a field for orgnization reigster secret
- [x] Display a message (to the user if they've been reigstered succesfully, but are not yet assigned a category)

### Cloud function (https):

- [x] Validates register secret
- [x] Validates user fields and creates a new user in firestore (if the fields are correct)
- [x] Sends an email to the admin that there's a new user in queue for approval (category assignment)

**Comment by ikusteu** [comment]
Hey @silviot, this is mostly implemented, but I see a small discrepancy between the implementation and the requirements mentioned here:

> The newly created user will have all categories associated with them, so the system should allow them to book any slot (until an admin comes in and assigns categories to restrict what they can book).

Currently the user can't book do anything until they've been assigned a category. Did we agree on that, or do you want it implemented as mentioned in the spec ☝️ ?
