### ISSUE TITLE
Allow admins to specify templates for emails that are sent out: 8 pts

### ISSUE THREAD

**Issue by silviot** [eisbuk/EisBuk#681]
Currently there's an email template in the admin preferences, but it has no effect.
We should change it with a version that allows templating and preview.

Admins should see the available placeholders (`${first-name}`, `${lsat-name}` etc) and see an example render of the template. Placeholders could be shown as buttons that, when clicked, fill in their text in the current cursor position.

## Tasks

- [ ] Solve this in the UI:
  - We can use the organisation preferences page
  - Replace `emailTemplate` field with `emailTemplates`
  - The saved templates could be shown as truncated text (cut off with "..." at the end)
  - The field should be clickable so that the modal with email templates gets opened
  - The modal could have a dropdown selection of all possible templates
  - The template currently edited (in modal) should render an input field for the template itself, short info message and a preview with dynamic fields replaced by some dummy values
  - The function used to process the template and show a preview can be reused later for constructing of an email message
  - The templates should be initialised with default values and submission of an empty form shouldn't be acceptable (both client side and firesore.rules)

- [ ]  Solve this in the data model:
  - The email templates should be stored as a record of template name and template value
  - The templates should be initialised with default values

- [ ] Consume these templates when sending out emails (should we move the template interpolation to a cloud function and send only the inputs: name, surname, etc) or interpolate on the client:
    - I would go with cloud function as some automatic emails might be triggered by an unauth user, so it makes sense to keep the templates to cloud function access

## Updated tasks

_I've kept the tasks above for reference_

- [x] Set up email payload types (with email template being retrieved using email type):
```typescript
// packages/shared/src/enums/email.ts
export enum EmailType {
  SendBookingsLink = "send-bookings-link",
  SendCalendarFile = "send-calendar-file",
  SendExtendedBookingLink = "send-extended-booking-link",
}

// packages/shared/src/types/email.ts
interface EmailTypePayload {
  [EmailType.SendBookingsLink]: {
    type: EmailType.SendBookingsLink;
    organization: string;
    customer: {
      name: string;
      surname: string;
      secretKey: string;
    };
  };
  [EmailType.SendCalendarFile]: {
    type: EmailType.SendCalendarFile;
    organization: string;
    customer: {
      name: string;
      surname: string;
      secretKey: string;
    };
  };
  [EmailType.SendExtendedBookingLink]: {
    type: EmailType.SendExtendedBookingLink;
    organization: string;
    bookingsMonth: string;
    extendedBookingsDate: string;
    customer: {
      name: string;
      surname: string;
    };
  };
}

export type ClientEmailPayload = {
  [T in EmailType]: EmailTypePayload[T];
};

// Usage: Implementing 'sendEmail' function consuming the client email payload (as a parameter)
const sendEmail = <T extends EmailType>(payload: ClientEmailPayload[T]) => {
  // If we do something like this, we get the correct type safety/intellisense with respect to 'type'
  if (payload.type === EmailType.SendExtendedBookingLink) {
    payload.extendedBookingsDate;
  }
};

// Usage: Calling the function, passing a client email payload as argument (intellisense will work, checking for correct type interface with respect to 'type')
sendEmail({
  type: EmailType.SendExtendedBookingLink,
  customer: { name: "", surname: "" },
  extendedBookingsDate: "",
  bookingsMonth: "",
  organization: "",
});

// Usage: Constructing the payload for the function (typing the variable)
const emailPayload: ClientEmailPayload[EmailType] = {
  type: EmailType.SendBookingsLink,
  customer: { name: "", surname: "", secretKey: "" },
  organization: "",
};
```

- [ ] set the default templates:

- organization preferences should be initialised with the default values (default email template for each email type)
- we can create a cloud function (sort of a migration) to update existing organizations (in production) with the default templates
- the defaults can be stored as `data` somewhere (probably shared package so that we can use them for testing: client + functions packages)
- when updating the template (using `admin_preferences` route), we shouldn't allow for empty values

- [x] update the `sendEmail` function to consume the templates:

_some of the work is already there, but to reiterate and update:_
- we should update the `sendEmail` to check the email type (maybe add a validation for the type)
- we should check auth for the type (the caller should either be an admin, or have secret key, depending on email type)
- the payload should be validated (with respect to email type)
- if successful, the sendEmail should construct and write the email as `payload` to the process document, thus triggering the delivery
