### ISSUE TITLE
Update running of dev environment with production data

### ISSUE THREAD

**Issue by ikusteu** [eisbuk/EisBuk#865]
In #857 I've made it possible to run dev build of client app with production data for eisbuk or igorice by running `rushx start:eisbuk` / `rushx start:igorice` respectively, but I would like to make some updates so that the DX is as frictionless as possible.

1. The script should be updated to add `test@eisbuk.it` to admins: I see that production has been changed so that `test@eisbuk.it` no longer an admin (which makes sense for production), so when we run the app locally with production data, it would make sense to add `test@eisbuk.it` to organization's `admins` field (we do it manually otherwise)

2. The `rushx start:<organization>` flow should look something like this (using igorice as example):
  - start the emulators
  - run `rushx start:igorice`
  - the script should check if we already have the backed up data from igorice:
    - if there's no data locally, it should pull data from the production db
    - if local data already exists it should fill the emulators with the data
    - if local data is stale (we want the latest data) we should be able to manually update the local backup (see point 3)

3. Rush repo commands should be updated so that backup and seeding (to emulators) of production data are two separate scripts (there should also be a different ticket to polish those commands)

### Tasks:

- [ ] Update the `start:<organization>` script to add `test@eisbuk.it` to organization's `admins`
- [ ] Update the start script to utilise local data (if exists)
- [ ] Break up `rush seed-firestore:<organization>` into two (`backup` and `seed`) scripts
