### ISSUE TITLE
Make the email checks case-insensitive

### ISSUE THREAD

**Issue by ikusteu** [eisbuk/EisBuk#880]
There was a problem where a customer signed up with `CUSTOMER.NAME@gmail.com`, the auth entry has been created and customer self registered. Afterwards, at some point, the customer tried logging in with `customer.name@gmail.com`. Since google auth is already case insensitive, the customer was able to authenticate, but since `findCustomerByEmail` looks for an exact match, the differently cased email didn't match and the customer was prompted to self register (rather than being redirected to their `/customer_area` page)

### Tasks

- [ ] Fix the issue at hand (finding customer by email should be case insensitive)
- [ ] For all future registrations, I think it would be nice to have all emails lowercased (when signing up) and stored in the db lowercased (this is just a preference and, if the 1st task is taken care of, shouldn't have any notable effect)
- [ ] Check for other possible bugs stemming from this inconsistency and make the functionality tolerate mismatches in casing, where it makes sense

_-note: it would probably be good to create a couple of string matching utils with different levels of strictness (in terms of whitespace, casing, etc...) and use those utils for string comparisons (in existing functionality and possible future one)._

**Comment by silviot** [comment]
My proposal for a plan involves making sure that emails are always normalized when stored: lowercased and stripped of any whitespace possibly present.

* [ ] Create a new function normalizeEmail that turns `  anExampleEmail@eXAMPLE.coM ` into `anexampleemail@example.com`.
* [ ]  change the code that stores emails into the db to normalize them before saving
* [ ] write a migration script to normalize all existing emails
* [ ] when searching for a matching email for user redirection, normalize it before querying firestore
